apiVersion: apps/v1
kind: Deployment
metadata:
  name: web 
  labels:
    app: deploy-web
spec:
  replicas: 3 # Колличество подов 
  selector:
    matchLabels:
      app: deploy-web
  template:
    metadata:
      labels:
        app: deploy-web
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
          name: port-nginx
      
      - name: multitool-container
        image: praqma/network-multitool:alpine-extra
        ports:
        - containerPort: 8080 
          name: port-multi
        env:
        - name: HTTP_PORT
          value: "8080"
