apiVersion: v1
kind: Service
metadata:
  name: service-web
  namespace: default
spec:
  type: NodePort
  selector:
    app: deploy-web
  ports:
  - name: web-pot-80
    protocol: TCP
    port: 8888
    nodePort: 31000
    targetPort: port-nginx

