volumes:
  data:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
  insight:

services:
  storage:
    image: minio/minio:latest
    container_name: storage
    command: server /data
    restart: always
    expose: 
      - 9000
    environment:
      MINIO_ROOT_USER: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${Storage_Secret:-STORAGE_SECRET_KEY}
      MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      # Рекомендуется использовать драйвер по умолчанию (json-file),
      # который Vector читает напрямую через docker.sock
       driver: json-file

  createbuckets:
    image: minio/mc
    container_name: mc
    depends_on:
      - storage
    restart: on-failure
    entrypoint: > 
      /bin/sh -c "      
      /usr/bin/mc alias set data http://storage:9000 ${Storage_AccessKey:-STORAGE_ACCESS_KEY} ${Storage_Secret:-STORAGE_SECRET_KEY} &&
      /usr/bin/mc mb --ignore-existing data/${Storage_Bucket:-data} &&
      /usr/bin/mc anonymous set download data/${Storage_Bucket:-data} &&
      exit 0;
      "

  uploader:
    build: ./uploader
    container_name: uploader
    depends_on:
      - storage
      - createbuckets
    expose: 
      - 3000
    environment:
      PORT: 3000
      S3_HOST: storage
      S3_PORT: 9000
      S3_ACCESS_KEY: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      S3_ACCESS_SECRET: ${Storage_Secret:-STORAGE_SECRET_KEY}
      S3_BUCKET: ${Storage_Bucket:-STORAGE_BUCKET}
    logging:
      # Рекомендуется использовать драйвер по умолчанию (json-file),
      # который Vector читает напрямую через docker.sock
       driver: json-file
  
  security:
    build: ./security
    container_name: security
    expose: 
      - 3000
    environment:
      PORT: 3000
    logging:
      # Рекомендуется использовать драйвер по умолчанию (json-file),
      # который Vector читает напрямую через docker.sock
       driver: json-file

  gateway:
    image: nginx:alpine
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"      
      - "8081:8080"
    depends_on:
      - storage
      - uploader
      - security
    logging:
      # Рекомендуется использовать драйвер по умолчанию (json-file),
      # который Vector читает напрямую через docker.sock
       driver: json-file

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0 # Use a specific version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for simplicity in development
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory as needed
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1        

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0 # Use a specific version, matching Elasticsearch
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  vector:
    image: timberio/vector:0.51.1-alpine # Use a specific version
    container_name: vector
    volumes:
      - ./vector/docker.yaml:/etc/vector/vector.yaml:ro  # Mount your Vector configuration
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this to a strong password
    depends_on:
      - prometheus
    restart: unless-stopped

  redis_1:
    image: redis:latest
    container_name: redis_1
    ports:
      - "6379:6379"

  insight:
    image: redis/redisinsight:latest
    container_name: insight
    restart: always
    depends_on:
      - redis_1
    ports:
      - "5540:5540"
    volumes:
      - insight:/data

