apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: deploy-web
spec:
  replicas: 2 # Колличество подов
  selector:
    matchLabels:
      app: deploy-web
  template:
    metadata:
      labels:
        app: deploy-web
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
          name: port-nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: configmap-nginx-html

      - name: multitool-container
        image: praqma/network-multitool:alpine-extra
        ports:
        - containerPort: 8080
          name: port-multi
        volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: configmap-multitool-html
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-multitool-env
              key: HTTP_PORT
      volumes:
      - name: configmap-multitool-html
        configMap:
          name: configmap-multitool-html
      - name: configmap-nginx-html
        configMap:
          name: configmap-nginx-html

