apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
subjects:
  - kind: User
    name: kvl
    apiGroup: rbac.authorization.k8s.io
roleRef: 
  kind: Role
  name: role-netology
  apiGroup: rbac.authorization.k8s.io
