apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: web
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2 
    ports:
    - containerPort: 8080
      name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: web
  ports:
  - name: netology-svc-port--web
    protocol: TCP
    port: 81
    targetPort: http-web-svc      
