apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: app
spec:
  selector:
    app: label-front
  ports:
  - name: web-port-80
    protocol: TCP
    port: 80
    targetPort: port
