apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deploy-front
  labels:
    app: deploy-web
spec:
  replicas: 6 # Колличество подов 
  selector:
    matchLabels:
      app: deploy-web
  template:
    metadata:
      labels:
        app: deploy-web
    spec:
      containers:
      - name: container-front
        image: nginx:latest
        ports:
        - containerPort: 80
          name: port-nginx
        volumeMounts:
        - name: volume-front
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: volume-front
        persistentVolumeClaim:
          claimName: pvc-vol-front
# scp -r html ubuntu@158.160.71.158:/home/ubuntu/
      
