apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-front
spec:
  volumeName: pv-vol-front
  storageClassName: "" 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
