apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "app.test.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-web-front
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: service-web-back
            port:
              number: 80
  - host: "app2.test.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-web-back
            port:
              number: 80
  - host: "netology.webhop.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 8080
      {{- if eq .Values.labels.service "deploy-test-web" }}
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 80
      {{- end }}
      {{- if eq .Values.labels.service "deploy-dev-web" }}
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 80
      {{- end }}
      {{- if eq .Values.labels.service "deploy-prod-web" }}
      - path: /prod
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: 80
      {{- end }}
  tls:
    - hosts:
      - netology.webhop.me
      secretName: secret-tls
