{{- if .Values.service.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
{{/*  name: service-web*/}}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
  - name: web-pot-80
    protocol: TCP
    port: 80
    targetPort: port-nginx
  - name: web-port-8080
    protocol: TCP
    port: 8080
    targetPort: port-multi
{{- end }}