apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol-front
spec:
  storageClassName: sc-vol
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
