apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "change nginx 1.290"
  name: deoloy
  labels:
    app: app
spec:
  replicas: 5 # Колличество подов
  strategy:
    type: RollingUpdate # Указываем тип стратегии
    rollingUpdate:
      maxUnavailable: 4 # Максимум 1 под может быть недоступен (или 25% от 3 = 0, но округляется вверх)
      maxSurge: 5       # Максимум 1 новый под может быть создан (или 25% от 3 = 0, но округляется вверх)
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.290
        ports:
        - containerPort: 80
          name: port-nginx

      - name: multitool-container
        image: praqma/network-multitool:alpine-extra
        ports:
        - containerPort: 8080
          name: port-multi
        env:
        - name: HTTP_PORT
          value: "8080"
