global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes itself
  - job_name: 'app_uploader'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['uploader:3000'] # или адрес вашего контейнера
    
  - job_name: 'app_security'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['security:3000'] # или адрес вашего контейнера
  - job_name: 'app_storage'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['storage:9000'] # или адрес вашего контейнера
#  - job_name: 'node_exporter'
#    static_configs:
#      - targets: ['node_exporter:9100'] # Example target for Node Exporter

