---
group_nexus:
  hosts:
    nexus:
      ansible_host: 84.252.129.75
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
group_agent:
  hosts:
    teamcity-agent:
      ansible_host: 62.84.119.234
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
group_server:
  hosts:
    teamcity-server:
      ansible_host: 89.169.131.224
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
