apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data  # ДОПОЛНИТЕ: Имя PVC
spec:
  volumeName: pv-data  # ДОПОЛНИТЕ: Имя PV, к которому будет привязан PVC, должен совпадать с созданным ранее PV
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi # ДОПОЛНИТЕ: Какой объём хранилища вы хотите передать в контейнер. Должно быть меньше или равно параметру storage из PV
