apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-data
provisioner: kubernetes.io/no-provisioner # ИНФОРМАЦИЯ: Нет автоматического развёртывания
volumeBindingMode: WaitForFirstConsumer

