apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-back
  labels:
    app: deploy-web
spec:
  replicas: 1 # Колличество подов 
  selector:
    matchLabels:
      app: deploy-web
  template:
    metadata:
      labels:
        app: deploy-web
    spec:
      containers:
      - name: multitool-container
        #image: praqma/network-multitool:alpine-extra
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 80
          name: port-multi
#       env:
#       - name: HTTP_PORT
#         value: "8080"
