apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deploy-front
  labels:
    app: deploy-web
spec:
  replicas: 3 # Колличество подов 
  selector:
    matchLabels:
      app: deploy-web
  template:
    metadata:
      labels:
        app: deploy-web
    spec:
      containers:
      - name: container-front
        image: nginx:latest
        ports:
        - containerPort: 80
          name: port-nginx
      
