apiVersion: v1
kind: Service
metadata:
  name: service-web-front
spec:
  selector:
    app: deploy-web
  ports:
  - name: web-pot-80
    protocol: TCP
    port: 80
    targetPort: port-nginx
# - name: web-port-8080
#   protocol: TCP
#   port: 9002
#   targetPort: port-multi
