apiVersion: v1
kind: Service
metadata:
  name: service-web-back
spec:
  selector:
    app: deploy-web
  ports:
  - name: web-port-80-back
    protocol: TCP
    port: 80
    targetPort: port-multi

#  - name: web-pot-80
#    protocol: TCP
#    port: 80
#    targetPort: port-nginx
